# Generated by Django 3.2.23 on 2024-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycar_backend', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_location',
            field=models.CharField(choices=[('Astana, Kazakhstan', 'Astana, Kazakhstan'), ('Almaty, Kazakhstan', 'Almaty, Kazakhstan'), ('Shymkent, Kazakhstan', 'Shymkent, Kazakhstan'), ('Karaganda, Kazakhstan', 'Karaganda, Kazakhstan'), ('Aktobe, Kazakhstan', 'Aktobe, Kazakhstan'), ('Taraz, Kazakhstan', 'Taraz, Kazakhstan'), ('Pavlodar, Kazakhstan', 'Pavlodar, Kazakhstan'), ('Ust-Kamenogorsk, Kazakhstan', 'Ust-Kamenogorsk, Kazakhstan'), ('Semey, Kazakhstan', 'Semey, Kazakhstan'), ('Atyrau, Kazakhstan', 'Atyrau, Kazakhstan'), ('Kostanay, Kazakhstan', 'Kostanay, Kazakhstan'), ('Kyzylorda, Kazakhstan', 'Kyzylorda, Kazakhstan'), ('Aktau, Kazakhstan', 'Aktau, Kazakhstan'), ('Kokshetau, Kazakhstan', 'Kokshetau, Kazakhstan'), ('Taldykorgan, Kazakhstan', 'Taldykorgan, Kazakhstan'), ('Ekibastuz, Kazakhstan', 'Ekibastuz, Kazakhstan'), ('Petropavl, Kazakhstan', 'Petropavl, Kazakhstan'), ('Oral, Kazakhstan', 'Oral, Kazakhstan'), ('Temirtau, Kazakhstan', 'Temirtau, Kazakhstan'), ('Turkestan, Kazakhstan', 'Turkestan, Kazakhstan')], default='Astana,Kazakhstan', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
